-- Create a table for storing financial data
CREATE TABLE financial_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Assets
    total_assets BIGINT,
    total_liquid_assets BIGINT,
    total_illiquid_assets BIGINT,
    net_liquid BIGINT,
    liquid_change BIGINT,
    outstanding_payments BIGINT,
    
    -- Guild Silver
    ocular_silver BIGINT,
    university_silver BIGINT,
    vanguard_silver BIGINT,
    
    -- Sellable Items
    total_liquid_items BIGINT,
    sellable_siv_ho BIGINT,
    sellable_delta_hq BIGINT,
    sellable_coast_hq BIGINT,
    sellable_martlock BIGINT,
    sellable_thetford BIGINT,
    sellable_lymhurst BIGINT,
    sellable_bridgewatch BIGINT,
    sellable_fort_sterling BIGINT,
    sellable_brecilien BIGINT,
    sellable_caerleon BIGINT,
    
    -- Illiquid Assets
    illiquid_siv_ho BIGINT,
    illiquid_delta_hq BIGINT,
    illiquid_coast_hq BIGINT,
    illiquid_martlock BIGINT,
    illiquid_thetford BIGINT,
    illiquid_lymhurst BIGINT,
    illiquid_bridgewatch BIGINT,
    illiquid_fort_sterling BIGINT,
    illiquid_brecilien BIGINT,
    illiquid_caerleon BIGINT,
    
    -- Membership
    total_members INT,
    total_active_members INT,
    ocular_members INT,
    university_members INT,
    vanguard_members INT,
    ocular_active_members INT,
    university_active_members INT,
    vanguard_active_members INT
);

-- Set up Row Level Security (RLS)
ALTER TABLE financial_data ENABLE ROW LEVEL SECURITY;

-- Create policy for anonymous read access
CREATE POLICY "Allow anonymous read access" 
    ON financial_data FOR SELECT 
    USING (true);

-- Create a secure table for writing new financial data (admin only)
CREATE TABLE financial_data_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submitted_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    processed BOOLEAN DEFAULT FALSE,
    
    -- Same fields as financial_data table
    -- Assets
    total_assets BIGINT,
    total_liquid_assets BIGINT,
    total_illiquid_assets BIGINT,
    net_liquid BIGINT,
    liquid_change BIGINT,
    outstanding_payments BIGINT,
    
    -- Guild Silver
    ocular_silver BIGINT,
    university_silver BIGINT,
    vanguard_silver BIGINT,
    
    -- Sellable Items
    total_liquid_items BIGINT,
    sellable_siv_ho BIGINT,
    sellable_delta_hq BIGINT,
    sellable_coast_hq BIGINT,
    sellable_martlock BIGINT,
    sellable_thetford BIGINT,
    sellable_lymhurst BIGINT,
    sellable_bridgewatch BIGINT,
    sellable_fort_sterling BIGINT,
    sellable_brecilien BIGINT,
    sellable_caerleon BIGINT,
    
    -- Illiquid Assets
    illiquid_siv_ho BIGINT,
    illiquid_delta_hq BIGINT,
    illiquid_coast_hq BIGINT,
    illiquid_martlock BIGINT,
    illiquid_thetford BIGINT,
    illiquid_lymhurst BIGINT,
    illiquid_bridgewatch BIGINT,
    illiquid_fort_sterling BIGINT,
    illiquid_brecilien BIGINT,
    illiquid_caerleon BIGINT,
    
    -- Membership
    total_members INT,
    total_active_members INT,
    ocular_members INT,
    university_members INT,
    vanguard_members INT,
    ocular_active_members INT,
    university_active_members INT,
    vanguard_active_members INT
);

-- Set up Row Level Security (RLS) for submissions
ALTER TABLE financial_data_submissions ENABLE ROW LEVEL SECURITY;

-- Create policy for authenticated users to insert
CREATE POLICY "Allow authenticated insert" 
    ON financial_data_submissions FOR INSERT 
    TO authenticated 
    WITH CHECK (true);
